version: 2.1
orbs:
    node: circleci/node@2.1.1
jobs:
    build-and-update-wiki:
        executor:
            name: node/default
        steps:
            - checkout
            - node/install-packages
            - run: git config --global user.email circleci@circleci
            - run: git config --global user.name CircleCI
            - run: git submodule update --init
            - run: npm run start
            - run: cd ./wiki && git checkout master && git add -A && (git diff-index --quiet HEAD || git commit -m "Compiled wiki" && git push)
            - run: git commit -am "Updated wiki submodule [skip ci]" && git push
workflows:
    build_and_update:
        jobs:
            - build-and-update-wiki:
                  filters:
                      branches:
                          only:
                              - master
